version: '3.8'
services:
 app:
  image: warehouse-app:latest
  build:
   context: .
   dockerfile: Dockerfile
  environment:
   - DB_USER=test
   - DB_PASSWORD=test
  depends_on:
   - db
  ports:
   - "8080:8080"


 db:
  image: postgres:13
  restart: always
  environment:
   POSTGRES_USER: test
   POSTGRES_PASSWORD: test
   POSTGRES_DB: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: