#file: noinspection SpringBootApplicationYaml
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    datasource:
      schema: classpath:db/changelog/products/sql/h2-init-sql
      ddl-auto: create-drop

      h2:
        console:
          enabled: true #http://localhost:8080/h2-console
  liquibase:
    enabled: false
