spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=warehouse
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.master.xml
    enabled: true
scheduler:
  timing: 100
  pricePercentage: 30
  enabled: false
  optimization: true
