spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehousedb
    username: ${USER}
    password: ${PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
  liquibase:
    changeLog: classpath:db/changelog/db.master.xml